config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'menus/index'
  root to: "tops#index"
  resources :menus
  resources :users,    only: [:show, :edit, :update, :destroy]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord

  validates :name,    presence: true
  validates :price,   presence: true
  validates :profile,  presence: true
  validates :image, presence: true

  has_one_attached :image
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one_attached :image
         has_many :menus

         validates :name,          presence: true,            length: {maximum: 25}
         validates :phone_number,  presence: true
         validates :money,         presence: true
         validates :access,        presence: true
         validates :holiday,       presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number, :access, :holiday, :word, :money, :image])
  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  before_action :set_item,  only: [:show, :edit, :update]
  def index
    @users = User.all
    @users = User.order("created_at DESC")
    @menus = Menu.all
    @menus = Menu.order("created_at DESC")
  end

  def show
    
  end

  def new
  @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to menus_path
    else
      render :new
    end
  end

  def edit

    unless user_signed_in? && current_user.id == @menu.user_id
      redirect_to action: :index
    end
  end

  def update

      if @menu.update(menu_params)
        redirect_to menu_path
       else
        render :edit
      end
  end

  def destroy
    menu = Menu.find(params[:id])
    menu.destroy
    redirect_to menus_path
end

  private

  def menu_params
    params.require(:menu).permit(:name,:image,:price,:profile).merge(user_id: current_user.id)
  end

  def set_item
    @menu = Menu.find(params[:id])
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  def index
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path
     else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    if user.destroy
      redirect_to root_path
     else
      render :show
    end
  end

  private

  def user_params
    params.require(:user).permit(:access, :holiday, :word, :money, :profile, :image)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DELIY FOO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/0995bb4a3e.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Rampart+One&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&family=Kaisei+HarunoUmi:wght@700&family=Rampart+One&family=Righteous&family=RocknRoll+One&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= image_tag("job.png", class: :logo1)%>
          </div>
        <div class="namel">
             <div class="name1">
               <%= "deliy foo" %>
             <%= image_tag("9379.png", class: :logol)%>
             </div>
        </div>
          <%= link_to image_tag("fish.png", class: :logo2), menus_path %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
    
      <%= link_to "Copyright © deliy foo All rights reserved.", new_user_registration_path, class: :copyright %>
      <%= link_to "※", destroy_user_session_path, method: :delete, class: :nav__logout %>
      <%= link_to ".", new_user_session_path, class: :nav__logout %>
    </footer>
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_with model: @menu, local: true do |f|%>
  <div class="field">
    <%= f.label :"商品名", "商品名" %><br />
    <%= f.text_field :name, id:"menu_name" %>
  </div>

  <div class="field">
    <%= f.label :"値段", "価格(半角数字のみでお願いします)" %><br />
    <%= f.text_area :price, class: :form__text, id:"menu_price" %>
  </div>

  <div class="field">
    <%= f.label :"商品説明", "商品の説明" %><br />
    <%= f.text_area :profile, class: :form__text, id:"menu_profile" %>
  </div>

  <div class="field">
    <%= f.label :"写真", "商品の写真" %><br />
    <%= f.file_field :image, id:"menu_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/menus/_menu.html.erb
<ul class="resipi">
<li class="card2">
  <%= link_to image_tag(menu.image, class: :card__img2 ), menu_path(menu.id) %>
  <div class="card__body">
    <%= link_to menu.name, menu_path(menu.id), class: :card__title%>
    <p class="card__summary">
      <%= menu.profile %>
    </p>
    <p class="card__summary">
      <%= menu.price %><%= "円"%>
    </p>
    <%= link_to menu.user.name, menu_path(menu.id), class: :card__user %>
  </div>
</li>
</ul>

app/views/menus/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: 'form', locals: { menu: @menu } %>
    </div>
  </div>
</div>

app/views/menus/index.html.erb
<div class="menusindex">
 <% if user_signed_in? %>
      <div class="greeting">
        <%= current_user.name%>
        <%= "様、おつかれさまです" %>
        <%=link_to image_tag("job1.png", class: :logo3), new_menu_path %>
        </div>
        <% else %>
        <div class="greeting">
        <%= "いらっしゃいませ" %>
        <%=image_tag("bag.png", class: :logo3)%>
      </div>
      <% end %>
 
      <ul class='lists'>
      <% @users.each do |user| %>
        <%= link_to user_path(user.id) do %>
        <li class='list'>
        <div class='image5'>
          <%= image_tag(user.image, class: "item-img")  %>
        </div>
        <div class='item-info'>
              <div class='item-name'>
               <%= user.name %>
              </div>
            <div class='item-price'>
                <%= "住所" %>
               <%= user.access %>
             </div>
            <div class='star-btn'>
               <%= "お店の定休日は月曜日" %>
               <%= user.holiday %>
                <%= "です" %>
             </div>
             <%= "ひとこと、" %>
             <div class='star-btn1'>
              <%= user.word %>
            </div>
           
          </div>
          </li>
        <% end %>
        <% end %>
          </ul>

            <% if @users.length == 0 %>
            <div class="card__wrapper">
            <div class="index2">
            <%= "登録されるまで少し待ってね〜" %>
            </div>
            </div>
            <% end %>

     <div class="card__wrapper">
         <div class="index">商品一覧</div>
     </div>

          <ul class='lists1'>
                <% @menus.each do |menu| %>
                <%= link_to menu_path(menu.id) do %>
              <li class='list1'>
                  <div class='image5'>
                       <div class="item_img0">
                             <%= link_to image_tag(menu.image.variant(resize: '220x220'),class: :item_img1), menu_path(menu.id)%>
                        </div>
                  </div>
                   <div class='item-info'>
                          <div class='item-setumei'>
                              <%= "商品名 " %>
                         </div>
                         <div class='item-setumei1'>
                            <%= menu.name %>
                         </div>
                         
                          <div class='item-setumei'>
                          <%= "商品説明" %>
                          </div>
                         <div class='item-name1'>
                            <%= menu.profile %>
                         </div>
                        <div class='item-price'>
                              <%= "価格" %>
                          <%= menu.price %><%= "円" %>
                         </div>
                       <%= link_to menu.user.name, menu_path(menu.id), class: :card__user %>
                    </div>
             </li>
        <% end %>
        <% end %>
          </ul>

</div>

app/views/menus/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <div class="page-heading">
      <h2>商品を載せてね〜</h2>
      <%= image_tag("4.png", class: :logo4) %>
      </div>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: 'form', locals: { menu: @menu } %>
    </div>
  </div>
</div>

app/views/menus/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
          <p class="prototype__hedding">
           <span>店名</span>
           <%= link_to @menu.user.name, user_path(@menu.user.id), class: :prototype__user %>
          </p>
      
      <%# メニューの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @menu.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_menu_path(@menu.id), class: :prototype__btn %>
          <%= link_to "削除する", menu_path(@menu.id), method: :delete,   class: :prototype__btn %>
        </div>
        <% end %>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
        <%= link_to image_tag(@menu.image,class: :syuhinimage), user_path(@menu.user.id)%>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">商品名</p>
          <p class="detail__message">
            <%= @menu.name %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">商品説明</p>
          <p class="detail__message">
            <%= @menu.profile %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">価格</p>
          <p class="detail__message">
            <%= @menu.price %><%= "円" %>
          </p>
        </div>
      </div>
     
    </div>
  </div>
</main>

app/views/tops/index.html.erb
<%#= link_to image_tag("ya.jpeg", class: :top1), menus_path %>
<div class="taiku">
  <div class="taiku0">
          <div class="taiku1">
            <%= "美 味 し い ご 飯 を 楽 し も う"%>
           </div>
          <div class="taiku2">
            <%= "テイクアウト掲載アプリ"%>
           </div>
          <%=link_to "deliy foo", menus_path, class: :taiku3 %>

  </div>
</div>

app/views/users/edit.html.erb
<%= form_with model: @user, local: true do |f|%>
  <div class="field">
    <%= f.label :"住所", "住所" %><br />
    <%= f.text_field :access, id:"menu_name" %>
  </div>

  <div class="field">
    <%= f.label :"定休日", "定休日" %><br />
    <%= f.text_area :holiday, class: :form__text, id:"menu_price" %>
  </div>

  <div class="field">
    <%= f.label :"店主からの一言", "店主からの一言" %><br />
    <%= f.text_area :word, class: :form__text, id:"menu_profile" %>
  </div>

  <div class="field">
    <%= f.label :"お支払い対応", "お支払い対応" %><br />
    <%= f.text_area :money, class: :form__text, id:"menu_profile" %>
  </div>

  <div class="field">
    <%= f.label :"お問合せ", "お問合せ" %><br />
    <%= f.text_area :phone_number, class: :form__text, id:"menu_profile" %>
  </div>

  <div class="field">
    <%= f.label :"写真", "商品の写真" %><br />
    <%= f.file_field :image, id:"menu_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
      <%= @user.name%>
        <%= "情報"%>
         </h2>

           <% if user_signed_in? && current_user.id == @user.id %>
              <div class="henns">
              <%= @user.name%>
              <%= "の"%>
              <%= link_to '登録内容編集',  edit_user_path(@user.id), method: :get, class: :uz_hennsyuu%>
              <%= link_to '削除', user_path(@user.id), method: :delete %>
              </div>
          <% end %>
     <div class="toiawase1">
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前 <i class="fas fa-store-alt"></i></th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">住所 <i class="fas fa-house-user"></i></th>
            <td class="table__col2"><%= @user.access %></td>
          </tr>
          <tr>
            <th class="table__col1">定休日 <i class="fas fa-bed"></i></th>
            <td class="table__col2"><%= @user.holiday %></td>
          </tr>
          <tr>
            <th class="table__col1">店主からの一言 <i class="far fa-star"></i></th>
            <td class="table__col2"><%= @user.word %></td>
          </tr>
          <tr>
            <th class="table__col1">お支払い対応 <i class="far fa-star"></i></th>
            <td class="table__col2"><%= @user.money %></td>
          </tr>
          <tr>
            <th class="table__col1">お問合せ <i class="fas fa-phone-square-alt"></i></th>
            <td class="table__col2"><%= @user.phone_number %>
          </tr>
        </tbody>
      </table>
        <div class="toiawase2">
              <%= image_tag @user.image, class: "toiawase3" %>
              <div class="toiawase">
                  <%= "←この番号から注文してね"%>
                </div>
       </div>
      </div>
      <h2 class="page-heading">
        <%= @user.name%>
        <%= "のテイクアイトメニュー"%>
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
        <%= render partial: 'menus/menu', collection: @user.menus %>
      </div>
    </div>
  </div>
</div>